---
# For conn
kafka_addr: localhost:9092
kafka_group_id: blah
kafka_topic: blah

kafka_num_partition: 2

# For Redis
redis_addr: localhost:6379
redis_pwd: ""
redis_db: 0
redis_queue_key: demoX_blah


# Mode
kafka_mode: false

